world: world
spawn_radius: 1000
center_x: 0
center_z: 0
radius: 2000
max_attempts: 500
logging_enabled: true
cooldown: 5
invincibility_duration: 5
apply_effects: true
send_title: true
blacklisted_blocks:
  - WATER
  - LAVA
allowed_surface_materials:
  - GRASS_BLOCK
  - DIRT
  - STONE
  - OAK_LEAVES
  - SAND
  - GRAVEL
  - SNOW_BLOCK
  - MYCELIUM
  - PODZOL
  - COARSE_DIRT
  - CLAY
  - SOUL_SAND
  - SOUL_SOIL
  - NETHERRACK
  - END_STONE
  - OBSIDIAN
  - BEDROCK
  - ICE
  - FROSTED_ICE
  - PACKED_ICE
  - BLUE_ICE
  - CONCRETE
  - TERRACOTTA
  - WHITE_TERRACOTTA
  - ORANGE_TERRACOTTA
  - MAGENTA_TERRACOTTA
  - LIGHT_BLUE_TERRACOTTA
  - YELLOW_TERRACOTTA
  - LIME_TERRACOTTA
  - PINK_TERRACOTTA
  - GRAY_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - CYAN_TERRACOTTA
  - PURPLE_TERRACOTTA
  - BLUE_TERRACOTTA
  - BROWN_TERRACOTTA
  - GREEN_TERRACOTTA
  - RED_TERRACOTTA
  - BLACK_TERRACOTTA
  - DEEPSLATE
  - GRASS_PATH
  - MYCELIUM
  - PODZOL
  - COARSE_DIRT
  - CLAY
  - SOUL_SAND
  - SOUL_SOIL
  - NETHERRACK
  - END_STONE
  - OBSIDIAN
  - BEDROCK
  - ICE
  - FROSTED_ICE
  - PACKED_ICE
  - BLUE_ICE
  - CONCRETE
  - TERRACOTTA
  - WHITE_TERRACOTTA
  - ORANGE_TERRACOTTA
  - MAGENTA_TERRACOTTA
  - LIGHT_BLUE_TERRACOTTA
  - YELLOW_TERRACOTTA
  - LIME_TERRACOTTA
  - PINK_TERRACOTTA
  - GRAY_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - CYAN_TERRACOTTA
  - PURPLE_TERRACOTTA
  - BLUE_TERRACOTTA
  - BROWN_TERRACOTTA
  - GREEN_TERRACOTTA
  - RED_TERRACOTTA
  - BLACK_TERRACOTTA
  - DEEPSLATE
  - GRASS_PATH
  - SAND
  - GRAVEL
  - SNOW_BLOCK